service: serverless-reminderService

provider:
  name: aws
  runtime: nodejs6.10
  iamRoleStatements:
    -  Effect: "Allow"
       Action:
         - "ses:*"
       Resource:
         - "*"
functions:
  dailyReminder:
    handler: handler.sendReminderByRate
    events:
      # Invoke the Lambda function everyday
      - schedule: rate(10 minutes)
  weekendReminder:
    handler: handler.sendReminderOnWeekend
    events:
      # Invoke the Lambda function every weekend at 1pm US/Eastern Time
      - schedule: cron(30 22 ? * SUN,SAT *)